<?php
/*
    PufferPanel - A Minecraft Server Management Panel
    Copyright (c) 2013 Dane Everitt
 
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see http://www.gnu.org/licenses/.
 */
session_start();
require_once('../../../../src/framework/framework.core.php');

if ($core->auth->isLoggedIn($_SERVER['REMOTE_ADDR'], $core->auth->getCookie('pp_auth_token'), $core->auth->getCookie('pp_server_hash')) === true)
{
    $baseUrl = "http://" .
        $core->server->nodeData('sftp_ip') . ":8003/gameservers/" .
        $core->server->getData('gsd_id');

    try {
        $response = GuzzleHttp\get($baseUrl . "/file/server.properties", [
            'headers' => [
                'X-Access-Token' => $core->server->nodeData('gsd_secret')
            ]
        ]);

        if ($response->getStatusCode() != 200) {
            exit("Unable to check whether server config exists!");
        }
    } catch (\GuzzleHttp\Exception\RequestException $ex) {
        /*
         * Create server.properties
         */
        $generateProperties = '
            #Minecraft Server Properties
            #Generated by PufferPanel
            generator-settings=
            op-permission-level=4
            allow-nether=true
            level-name=world
            enable-query=true
            allow-flight=false
            announce-player-achievements=true
            server-port='.$core->server->getData('server_port').'
            query.port='.$core->server->getData('server_port').'
            level-type=DEFAULT
            enable-rcon=false
            force-gamemode=false
            level-seed=
            server-ip='.$core->server->getData('server_ip').'
            max-build-height=256
            spawn-npcs=true
            white-list=false
            debug=false
            spawn-animals=true
            texture-pack=
            snooper-enabled=true
            hardcore=false
            online-mode=true
            resource-pack=
            pvp=true
            difficulty=1
            enable-command-block=false
            gamemode=1
            player-idle-timeout=0
            max-players=20
            spawn-monsters=true
            generate-structures=true
            view-distance=10
            spawn-protection=16
            motd=Powered by Firebird-hosting
        ';

        $response = GuzzleHttp\put($baseUrl . "/file/server.properties", [
            'headers' => [
                'X-Access-Token' => $core->server->nodeData('gsd_secret')
            ],
            'body'    => [
                'contents' => $generateProperties
            ]
        ]);

        $responseText = $response->getBody();

        if(!empty($responseText)) {
            exit("An error was encountered with this AJAX request. Unable to make server.properties.");
        }

        $core->log->getUrl()->addLog(0, 1, array('system.create_serverprops', 'A new server.properties file was created for your server.'));
    }

    /*
	 * Connect and Run Function
	 */
    $response = GuzzleHttp\get($baseUrl . "/on", [
        'headers' => [
            'X-Access-Token' => $core->server->nodeData('gsd_secret')
        ]
    ]);

    if ($response->getBody() != "\"ok\"") {
		exit("There was an error while trying to power on your servers!");
    }

	/*
	 * Run CPU Limit
	 * cpulimit -p #### -l #### -d
	 *
	 * This is super buggy.
	 */
	if ($core->server->getData('cpu_limit') > 0) {
        $response = GuzzleHttp\get($baseUrl, [
            'headers' => [
                'X-Access-Token' => $core->server->nodeData('gsd_secret')
            ]
        ]);

        $jsonData = $response->json();

		if(!array_key_exists('pid', $jsonData)) {
				exit("Unable to get PID. Server has been started.");
        }

		$core
            ->ssh
            ->generateSSH2Connection($core->server->nodeData('id'), true)
            ->executeSSH2Command('sudo cpulimit -p ' . $jsonData['pid'] . ' -l ' . $core->server->getData('cpu_limit') . ' -d');
	}

	echo 'ok';
} else {
	die('Invalid Authentication.');
}
